# Generated by Django 4.2.20 on 2026-04-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password_hash', models.CharField(blank=True, default='', max_length=255)),
                ('rol', models.CharField(choices=[('admin', 'Admin'), ('asesor', 'Asesor')], default='asesor', max_length=20)),
                ('color', models.CharField(default='#ec4899', max_length=20)),
                ('especialidad', models.CharField(blank=True, default='', max_length=200)),
                ('local_tienda', models.CharField(blank=True, default='', max_length=200)),
                ('max_chats', models.IntegerField(default=10)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'advisors',
                'ordering': ['nombre'],
            },
        ),
    ]
