# Generated by Django 4.2.20 on 2026-04-10 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='en_turno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advisor',
            name='ultimo_check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='ultimo_check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AdvisorTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('duracion_minutos', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='accounts.advisor')),
            ],
            options={
                'db_table': 'advisor_turnos',
                'ordering': ['-check_in'],
            },
        ),
    ]
