# Generated by Django 4.2.20 on 2026-04-01 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_phone', models.CharField(db_index=True, max_length=20)),
                ('remote_name', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.TextField()),
                ('direction', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=10)),
                ('is_ai_response', models.BooleanField(default=False)),
                ('sent_via', models.CharField(blank=True, default='evolution', max_length=20)),
                ('delivery_status', models.CharField(blank=True, default='sent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'chats',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationOrigen',
            fields=[
                ('remote_phone', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('origen', models.CharField(default='directo', max_length=50)),
                ('detalle', models.CharField(blank=True, default='', max_length=500)),
                ('detectado_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'conversation_origen',
            },
        ),
        migrations.CreateModel(
            name='InternalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_phone', models.CharField(db_index=True, max_length=20)),
                ('advisor_nombre', models.CharField(blank=True, default='', max_length=200)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advisor', models.ForeignKey(blank=True, db_column='advisor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.advisor')),
            ],
            options={
                'db_table': 'internal_notes',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_phone', models.CharField(db_index=True, max_length=20, unique=True)),
                ('remote_name', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('sin_responder', 'Sin responder'), ('ia_atendido', 'IA Atendido'), ('necesita_asesor', 'Necesita Asesor'), ('asignado', 'Asignado'), ('resuelto', 'Resuelto')], db_index=True, default='sin_responder', max_length=20)),
                ('outcome', models.CharField(choices=[('pendiente', 'Pendiente'), ('venta_cerrada', 'Venta cerrada'), ('venta_perdida', 'Venta perdida')], default='pendiente', max_length=20)),
                ('needs_human', models.BooleanField(default=False)),
                ('first_response_seconds', models.IntegerField(blank=True, null=True)),
                ('origen', models.CharField(blank=True, default='directo', max_length=50)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advisor', models.ForeignKey(blank=True, db_column='advisor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.advisor')),
            ],
            options={
                'db_table': 'conversations',
            },
        ),
    ]
