# Generated by Django 4.2.20 on 2026-04-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.IntegerField(blank=True, null=True)),
                ('template_id', models.IntegerField(blank=True, null=True)),
                ('contenido', models.TextField()),
                ('tipo', models.CharField(choices=[('individual', 'Individual'), ('masivo', 'Masivo')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('fallido', 'Fallido'), ('programado', 'Programado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('batch_id', models.CharField(blank=True, db_index=True, default='', max_length=36)),
                ('error_msg', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuickReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('categoria', models.CharField(default='general', max_length=50)),
                ('contenido', models.TextField()),
                ('advisor_id', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'quick_replies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('promocion', 'Promocion'), ('nueva_coleccion', 'Nueva Coleccion'), ('estado_pedido', 'Estado de Pedido'), ('bienvenida', 'Bienvenida'), ('descuento', 'Descuento'), ('personalizado', 'Personalizado')], max_length=30)),
                ('contenido', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'templates',
                'ordering': ['-created_at'],
            },
        ),
    ]
