# Generated by Django 4.2.20 on 2026-04-10 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuickReply',
        ),
    ]
