# Generated by Django 4.2.20 on 2026-04-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('groq', 'Groq'), ('gemini', 'Gemini')], default='openai', max_length=20)),
                ('api_key', models.CharField(blank=True, default='', max_length=500)),
                ('model', models.CharField(default='gpt-4o-mini', max_length=100)),
                ('system_prompt', models.TextField(default='Eres la asistente virtual de Clemencia Brand, una tienda de ropa femenina. Responde de forma amable, breve y profesional. Ayuda con consultas sobre productos, precios, horarios y pedidos. Si no sabes algo, indica que un asesor se comunicara pronto. Responde en espanol.')),
                ('max_tokens', models.IntegerField(default=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_settings',
            },
        ),
    ]
