# Generated by Django 4.2.20 on 2026-04-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertasConfig',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('minutos_sin_responder', models.IntegerField(default=15)),
                ('activo', models.BooleanField(default=True)),
                ('notificar_admin', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'alertas_config',
            },
        ),
    ]
