# Generated by Django 4.2.20 on 2026-04-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(default='general', max_length=50)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('keywords', models.TextField(blank=True, default='')),
                ('filename', models.CharField(max_length=255)),
                ('filepath', models.CharField(max_length=255)),
                ('filesize', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('downloads', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'catalogs',
                'ordering': ['-created_at'],
            },
        ),
    ]
