# Generated by Django 4.2.20 on 2026-04-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VentaCerrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_phone', models.CharField(db_index=True, max_length=20)),
                ('remote_name', models.CharField(blank=True, default='', max_length=200)),
                ('advisor_id', models.IntegerField(blank=True, null=True)),
                ('advisor_nombre', models.CharField(blank=True, default='', max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metodo_pago', models.CharField(blank=True, default='', max_length=50)),
                ('productos_descripcion', models.TextField(blank=True, default='')),
                ('comprobante_url', models.CharField(blank=True, default='', max_length=500)),
                ('notas', models.TextField(blank=True, default='')),
                ('origen', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'ventas_cerradas',
            },
        ),
    ]
